import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    nav_dashboard: 'Dashboard',
    nav_requests: 'Requests',
    nav_users: 'Users',
    nav_cabs: 'Cabs',
    nav_routes: 'Routes',
    nav_tracking: 'Live Tracking',
    nav_my_dashboard: 'My Dashboard',
    nav_my_requests: 'My Requests',
    hdr_english: 'English',
    hdr_notifications: 'Notifications',
    hdr_mark_all_read: 'Mark all read',
    hdr_no_notifications: 'No notifications',
    hdr_profile: 'Profile',
    hdr_logout: 'Logout',
    hdr_greeting: 'Hi',
    hdr_notification_fallback: 'Notification',
    nav_track_my_cab: 'Track My Cab',
    common_connected: 'Connected',
    common_disconnected: 'Disconnected',
    dash_title: 'Dashboard',
    dash_welcome: 'Welcome to AISIN Fleet Management',
    dash_refresh: 'Refresh',
    dash_total_users: 'Total Users',
    dash_total_cabs: 'Total Cabs',
    dash_active_routes: 'Active Routes',
    dash_pending_requests: 'Pending Requests',
    dash_recent_requests: 'Recent Requests',
    dash_view_all: 'View all',
    dash_no_recent_requests: 'No recent requests',
    dash_today_summary: "Today's Summary",
    dash_total_requests: 'Total Requests',
    dash_active_cabs: 'Active Cabs',
    dash_pending: 'Pending',
    dash_quick_actions: 'Quick Actions',
    dash_manage_routes: 'Manage Routes',
    dash_live_tracking: 'Live Tracking',
    dash_add_new_user: 'Add New User'
    ,
    login_title: 'Fleet Management System',
    login_subtitle: 'Vehicle request management with real-time tracking',
    login_welcome: 'Welcome',
    login_signin: 'Sign in to continue',
    login_email: 'Email',
    login_password: 'Password',
    login_email_placeholder: 'Enter your email',
    login_password_placeholder: 'Enter your password',
    login_signing_in: 'Signing in...',
    login_button: 'Login',
    login_help: 'Contact your HR administrator if you need access',
    login_err_required: 'Please enter both email and password',
    login_driver_name: 'Driver Name',
    login_driver_name_placeholder: 'Enter driver name',
    login_driver_section: 'Driver Login',
    login_microsoft: 'Continue with Microsoft',
    login_microsoft_signing_in: 'Redirecting to Microsoft...',
    users_manage_desc: 'Manage system users and their roles',
    users_create: 'Create User',
    users_empty_desc: 'Get started by creating a new user',
    users_edit: 'Edit User',
    users_create_new: 'Create New User',
    cabs_manage_desc: 'Manage fleet vehicles',
    cabs_add: 'Add Cab',
    cabs_empty_desc: 'Add your first cab to the fleet',
    cabs_edit: 'Edit Cab',
    cabs_add_new: 'Add New Cab',
    routes_manage_desc: 'Manage transportation routes',
    routes_create: 'Create Route',
    routes_empty_desc: 'Create your first route to get started',
    routes_edit: 'Edit Route',
    routes_create_new: 'Create New Route',
    requests_manage_my_desc: 'Manage your cab requests',
    requests_manage_all_desc: 'Manage all cab requests',
    requests_new: 'New Request',
    requests_new_cab: 'New Cab Request',
    requests_edit: 'Edit Request',
    requests_empty_desc: 'Submit a new request to get started',
    requests_approved: 'Approved',
    search_users: 'Search users...',
    search_cabs: 'Search cabs...',
    search_routes: 'Search routes...',
    search_requests: 'Search requests...',
    all_roles: 'All Roles',
    all_status: 'All Status',
    employee_manage_desc: 'Manage your cab requests and track your trips',
    notifications_unread: 'Unread Notifications',
    driver_dashboard: 'Driver Dashboard',
    driver_your_cab: 'Your Cab',
    driver_location_tracking: 'Location Tracking',
    driver_enable_location_sharing: 'Enable Location Sharing',
    driver_location_intro: 'To provide real-time tracking and efficient cab allocation, we need access to your location. This helps employees know when their cab will arrive.',
    driver_location_denied: 'Location Access Denied',
    driver_location_enable_browser: 'Please enable location access in your browser settings:',
    driver_location_step1: 'Click the lock/info icon in the address bar',
    driver_location_step2: 'Find "Location" in the permissions list',
    driver_location_step3: 'Change it to "Allow"',
    driver_location_step4: 'Refresh this page',
    driver_location_how_it_works: 'How it works:',
    driver_location_point1: "Your location is shared only when you're on duty",
    driver_location_point2: 'Employees can see your cab approaching',
    driver_location_point3: 'HR can monitor route progress',
    driver_location_point4: 'Location data is encrypted and secure',
    driver_requesting_access: 'Requesting Access...',
    driver_check_permission: 'Check Permission Again',
    driver_enable_location_access: 'Enable Location Access',
    driver_default_pickup: 'Default pickup',
    driver_status_waiting: 'Waiting',
    driver_status_boarded: 'Boarded',
    driver_status_dropped: 'Dropped',
    driver_status_no_show: 'No Show',
    driver_action_call: 'Call',
    driver_action_board: 'Board',
    driver_action_no_show: 'No Show',
    driver_action_drop: 'Drop Off',
    driver_welcome: 'Welcome',
    driver_online: 'Online',
    driver_offline: 'Offline',
    driver_status_label: 'Status',
    driver_seats: 'seats',
    driver_no_cab_assigned: 'No cab assigned to you',
    driver_contact_hr_for_cab: 'Contact HR to get a cab assigned',
    driver_current_location: 'Current Location',
    driver_accuracy: 'Accuracy',
    driver_start_tracking: 'Start Tracking',
    driver_stop_tracking: 'Stop Tracking',
    driver_tracking_active: 'Location is being shared in real-time',
    driver_todays_route: "Today's Route",
    driver_estimated_time: 'Estimated time',
    driver_minutes: 'minutes',
    driver_passengers: 'Passengers',
    driver_no_passengers_today: 'No passengers assigned for today',
    employee_connected_realtime: 'Connected - Real-time updates active',
    employee_disconnected_reconnecting: 'Disconnected - Reconnecting...',
    employee_todays_trip: "Today's Trip",
    employee_pickup_at: 'Pickup at',
    employee_to: 'To',
    employee_my_requests: 'My Requests',
    employee_no_requests: 'No requests yet',
    employee_create_first_request: 'Create your first request',
    employee_assigned: 'Assigned',
    employee_at: 'at',
    employee_cancel: 'Cancel',
    employee_notifications_title: 'Notifications',
    employee_no_notifications: 'No notifications',
    employee_new_cab_request: 'New Cab Request',
    employee_pickup_date: 'Pickup Date',
    employee_pickup_time: 'Pickup Time',
    employee_pickup_location: 'Pickup Location',
    employee_drop_location: 'Drop Location',
    employee_notes_optional: 'Notes (Optional)',
    employee_enter_pickup: 'Enter pickup address',
    employee_enter_drop: 'Enter drop address',
    employee_special_instructions: 'Any special instructions...',
    employee_submitting: 'Submitting...',
    employee_submit_request: 'Submit Request',
    employee_track_cab_title: 'Track My Cab',
    employee_track_cab_subtitle: 'Live route view for your assigned commute cab.',
    employee_no_trip_title: 'No trip available',
    employee_no_trip_desc: 'Your daily trip has not been assigned yet.',
    employee_back_dashboard: 'Back to Dashboard',
    common_back: 'Back',
    common_refresh: 'Refresh',
    tracking_trip_details: 'Trip Details',
    tracking_cab_status: 'Cab Status',
    tracking_route_stops: 'Route Stops',
    tracking_pickup: 'Pickup',
    tracking_boarding_point: 'Boarding point',
    tracking_office: 'Office',
    tracking_destination: 'Destination',
    tracking_next_stop: 'Next stop',
    tracking_distance_to_boarding: 'Distance to boarding point',
    tracking_distance_to_office: 'Distance to office',
    tracking_last_location_update: 'Last location update',
    tracking_waiting_assignment: 'Waiting for cab assignment',
    tracking_cab_not_assigned: 'Cab is not assigned yet. Tracking will appear automatically once the trip is allocated.',
    tracking_route_not_configured: 'Route stops are not configured with the route yet.',
    tracking_progress_at_boarding: 'Cab has reached your boarding point',
    tracking_progress_left_boarding: 'Cab has left the boarding point',
    tracking_progress_coming_boarding: 'Cab is coming to your boarding point',
    tracking_progress_at_office_boarding: 'Cab is at AISIN boarding point',
    tracking_progress_left_office_boarding: 'Cab has left AISIN boarding point',
    tracking_progress_coming_office_boarding: 'Cab is coming to AISIN boarding point',
    tracking_progress_at_office: 'Cab is currently at AISIN office',
    requests_no_results: 'No requests found',
    requests_assign_cab: 'Assign Cab',
    requests_assigning: 'Assigning...',
    requests_approve: 'Approve',
    requests_pending: 'Pending',
    requests_in_progress: 'In Progress',
    requests_completed: 'Completed',
    requests_cancelled: 'Cancelled',
    requests_no_cabs: 'No available cabs',
    requests_select_route: 'Select a route',
    requests_pickup_time: 'Pickup Time',
    requests_pickup_location: 'Pickup Location',
    requests_drop_location: 'Drop Location',
    requests_notes: 'Notes',
    requests_submit: 'Submit Request',
    requests_update: 'Update Request',
    requests_saving: 'Saving...',
    requests_route_required: 'Route is required',
    requests_pickup_time_required: 'Pickup time is required',
    requests_employee_label: 'Employee',
    requests_route_label: 'Route',
    requests_select_available_cab: 'Select Available Cab',
    requests_no_driver: 'No driver',
    requests_not_set: 'Not set',
    profile_shift: 'Shift',
    tracking_all_cabs: 'All Cabs',
    tracking_tracked: 'tracked',
    profile_info: 'Profile Information',
    profile_change_password: 'Change Password'
  },
  ja: {
    nav_dashboard: 'ダッシュボード',
    nav_requests: 'リクエスト',
    nav_users: 'ユーザー',
    nav_cabs: '車両',
    nav_routes: 'ルート',
    nav_tracking: 'ライブ追跡',
    nav_my_dashboard: 'マイダッシュボード',
    nav_my_requests: 'マイリクエスト',
    hdr_english: '日本語',
    hdr_notifications: '通知',
    hdr_mark_all_read: 'すべて既読',
    hdr_no_notifications: '通知はありません',
    hdr_profile: 'プロフィール',
    hdr_logout: 'ログアウト',
    dash_title: 'ダッシュボード',
    dash_welcome: 'AISIN フリート管理へようこそ',
    dash_refresh: '更新',
    dash_total_users: 'ユーザー数',
    dash_total_cabs: '車両数',
    dash_active_routes: '有効ルート',
    dash_pending_requests: '保留中リクエスト',
    dash_recent_requests: '最近のリクエスト',
    dash_view_all: 'すべて表示',
    dash_no_recent_requests: '最近のリクエストはありません',
    dash_today_summary: '本日のサマリー',
    dash_total_requests: '総リクエスト',
    dash_active_cabs: '稼働中車両',
    dash_pending: '保留',
    dash_quick_actions: 'クイック操作',
    dash_manage_routes: 'ルート管理',
    dash_live_tracking: 'ライブ追跡',
    dash_add_new_user: '新規ユーザー追加'
    ,
    login_title: 'フリート管理システム',
    login_subtitle: 'リアルタイム追跡付きの車両申請管理',
    login_welcome: 'ようこそ',
    login_signin: 'サインインして続行',
    login_email: 'メール',
    login_password: 'パスワード',
    login_email_placeholder: 'メールを入力',
    login_password_placeholder: 'パスワードを入力',
    login_signing_in: 'サインイン中...',
    login_button: 'ログイン',
    login_help: 'アクセスが必要な場合は管理者へ連絡してください',
    login_err_required: 'メールとパスワードを入力してください'
  },
  ta: {
    nav_dashboard: 'டாஷ்போர்டு',
    nav_requests: 'கோரிக்கைகள்',
    nav_users: 'பயனர்கள்',
    nav_cabs: 'கார்கள்',
    nav_routes: 'பாதைகள்',
    nav_tracking: 'நேரடி கண்காணிப்பு',
    nav_my_dashboard: 'என் டாஷ்போர்டு',
    nav_my_requests: 'என் கோரிக்கைகள்',
    hdr_english: 'தமிழ்',
    hdr_notifications: 'அறிவிப்புகள்',
    hdr_mark_all_read: 'அனைத்தும் படித்ததாக குறி',
    hdr_no_notifications: 'அறிவிப்புகள் இல்லை',
    hdr_profile: 'சுயவிவரம்',
    hdr_logout: 'வெளியேறு',
    dash_title: 'டாஷ்போர்டு',
    dash_welcome: 'AISIN வாகன மேலாண்மைக்கு வரவேற்கிறோம்',
    dash_refresh: 'புதுப்பிக்க',
    dash_total_users: 'மொத்த பயனர்கள்',
    dash_total_cabs: 'மொத்த கார்கள்',
    dash_active_routes: 'செயலில் உள்ள பாதைகள்',
    dash_pending_requests: 'நிலுவை கோரிக்கைகள்',
    dash_recent_requests: 'சமீப கோரிக்கைகள்',
    dash_view_all: 'அனைத்தும் காண்க',
    dash_no_recent_requests: 'சமீப கோரிக்கைகள் இல்லை',
    dash_today_summary: 'இன்றைய சுருக்கம்',
    dash_total_requests: 'மொத்த கோரிக்கைகள்',
    dash_active_cabs: 'செயலில் உள்ள கார்கள்',
    dash_pending: 'நிலுவை',
    dash_quick_actions: 'விரைவு செயல்கள்',
    dash_manage_routes: 'பாதைகள் மேலாண்மை',
    dash_live_tracking: 'நேரடி கண்காணிப்பு',
    dash_add_new_user: 'புதிய பயனர் சேர்க்க'
    ,
    login_title: 'வாகன மேலாண்மை அமைப்பு',
    login_subtitle: 'நேரடி கண்காணிப்புடன் வாகன கோரிக்கை மேலாண்மை',
    login_welcome: 'வரவேற்கிறோம்',
    login_signin: 'தொடர உள்நுழைக',
    login_email: 'மின்னஞ்சல்',
    login_password: 'கடவுச்சொல்',
    login_email_placeholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    login_password_placeholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    login_signing_in: 'உள்நுழைகிறது...',
    login_button: 'உள்நுழை',
    login_help: 'அணுகல் தேவையெனில் HR நிர்வாகியை தொடர்பு கொள்ளவும்',
    login_err_required: 'மின்னஞ்சல் மற்றும் கடவுச்சொல் இரண்டும் அவசியம்'
  },
  hi: {
    nav_dashboard: 'डैशबोर्ड',
    nav_requests: 'अनुरोध',
    nav_users: 'उपयोगकर्ता',
    nav_cabs: 'कैब',
    nav_routes: 'रूट',
    nav_tracking: 'लाइव ट्रैकिंग',
    nav_my_dashboard: 'मेरा डैशबोर्ड',
    nav_my_requests: 'मेरे अनुरोध',
    hdr_english: 'हिंदी',
    hdr_notifications: 'सूचनाएं',
    hdr_mark_all_read: 'सभी पढ़ा हुआ करें',
    hdr_no_notifications: 'कोई सूचना नहीं',
    hdr_profile: 'प्रोफाइल',
    hdr_logout: 'लॉगआउट',
    dash_title: 'डैशबोर्ड',
    dash_welcome: 'AISIN फ्लीट मैनेजमेंट में आपका स्वागत है',
    dash_refresh: 'रीफ्रेश',
    dash_total_users: 'कुल उपयोगकर्ता',
    dash_total_cabs: 'कुल कैब',
    dash_active_routes: 'सक्रिय रूट',
    dash_pending_requests: 'लंबित अनुरोध',
    dash_recent_requests: 'हाल के अनुरोध',
    dash_view_all: 'सभी देखें',
    dash_no_recent_requests: 'कोई हालिया अनुरोध नहीं',
    dash_today_summary: 'आज का सारांश',
    dash_total_requests: 'कुल अनुरोध',
    dash_active_cabs: 'सक्रिय कैब',
    dash_pending: 'लंबित',
    dash_quick_actions: 'त्वरित कार्य',
    dash_manage_routes: 'रूट प्रबंधन',
    dash_live_tracking: 'लाइव ट्रैकिंग',
    dash_add_new_user: 'नया उपयोगकर्ता जोड़ें'
    ,
    login_title: 'फ्लीट मैनेजमेंट सिस्टम',
    login_subtitle: 'रियल-टाइम ट्रैकिंग के साथ वाहन अनुरोध प्रबंधन',
    login_welcome: 'स्वागत है',
    login_signin: 'जारी रखने के लिए साइन इन करें',
    login_email: 'ईमेल',
    login_password: 'पासवर्ड',
    login_email_placeholder: 'अपना ईमेल दर्ज करें',
    login_password_placeholder: 'अपना पासवर्ड दर्ज करें',
    login_signing_in: 'साइन इन हो रहा है...',
    login_button: 'लॉगिन',
    login_help: 'एक्सेस के लिए HR एडमिन से संपर्क करें',
    login_err_required: 'कृपया ईमेल और पासवर्ड दर्ज करें'
  },
  kn: {
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    nav_requests: 'ವಿನಂತಿಗಳು',
    nav_users: 'ಬಳಕೆದಾರರು',
    nav_cabs: 'ಕ್ಯಾಬ್‌ಗಳು',
    nav_routes: 'ಮಾರ್ಗಗಳು',
    nav_tracking: 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    nav_my_dashboard: 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    nav_my_requests: 'ನನ್ನ ವಿನಂತಿಗಳು',
    hdr_english: 'ಕನ್ನಡ',
    hdr_notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    hdr_mark_all_read: 'ಎಲ್ಲವನ್ನು ಓದಿದಂತೆ ಗುರುತುಮಾಡಿ',
    hdr_no_notifications: 'ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    hdr_profile: 'ಪ್ರೊಫೈಲ್',
    hdr_logout: 'ಲಾಗ್‌ಔಟ್',
    dash_title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    dash_welcome: 'AISIN ಫ್ಲೀಟ್ ಮ್ಯಾನೇಜ್ಮೆಂಟ್‌ಗೆ ಸ್ವಾಗತ',
    dash_refresh: 'ರಿಫ್ರೆಶ್',
    dash_total_users: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    dash_total_cabs: 'ಒಟ್ಟು ಕ್ಯಾಬ್‌ಗಳು',
    dash_active_routes: 'ಸಕ್ರಿಯ ಮಾರ್ಗಗಳು',
    dash_pending_requests: 'ಬಾಕಿ ವಿನಂತಿಗಳು',
    dash_recent_requests: 'ಇತ್ತೀಚಿನ ವಿನಂತಿಗಳು',
    dash_view_all: 'ಎಲ್ಲವನ್ನು ನೋಡಿ',
    dash_no_recent_requests: 'ಇತ್ತೀಚಿನ ವಿನಂತಿಗಳಿಲ್ಲ',
    dash_today_summary: 'ಇಂದಿನ ಸಾರಾಂಶ',
    dash_total_requests: 'ಒಟ್ಟು ವಿನಂತಿಗಳು',
    dash_active_cabs: 'ಸಕ್ರಿಯ ಕ್ಯಾಬ್‌ಗಳು',
    dash_pending: 'ಬಾಕಿ',
    dash_quick_actions: 'ವೇಗವಾದ ಕ್ರಮಗಳು',
    dash_manage_routes: 'ಮಾರ್ಗ ನಿರ್ವಹಣೆ',
    dash_live_tracking: 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    dash_add_new_user: 'ಹೊಸ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ'
    ,
    login_title: 'ಫ್ಲೀಟ್ ಮ್ಯಾನೇಜ್ಮೆಂಟ್ ಸಿಸ್ಟಮ್',
    login_subtitle: 'ರಿಯಲ್-ಟೈಮ್ ಟ್ರ್ಯಾಕಿಂಗ್‌ನೊಂದಿಗೆ ವಾಹನ ವಿನಂತಿ ನಿರ್ವಹಣೆ',
    login_welcome: 'ಸ್ವಾಗತ',
    login_signin: 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    login_email: 'ಇಮೇಲ್',
    login_password: 'ಪಾಸ್ವರ್ಡ್',
    login_email_placeholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    login_password_placeholder: 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    login_signing_in: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    login_button: 'ಲಾಗಿನ್',
    login_help: 'ಅನುಮತಿ ಬೇಕಿದ್ದರೆ HR ಆಡ್ಮಿನ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ',
    login_err_required: 'ದಯವಿಟ್ಟು ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('preferred_language') || 'en');

  useEffect(() => {
    localStorage.setItem('preferred_language', language);
  }, [language]);

  const t = useMemo(() => {
    return (key) => {
      const localized = translations[language]?.[key];
      if (localized) return localized;
      return translations.en[key] || key;
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
